name: expense 
version: '3.8'
networks:
  default:
    name: expense 
services:
    mysql:
      image: kedarnath9988/mysql:1.0 
      container_name: mysql 
    backend:
      image: kedarnath9988/backend:1.0 
      container_name: backend
      command: sh -c "sleep 20 && /opt/app "
      depends_on:
        - mysql 
    frontend:
      image: kedarnath9988/frontend:1.0 
      container_name: frontend
      depends_on:
        - backend
      ports:
        - "80:80"
