name: expense 
networks:
  default:
    name: expense 
volumes:
  default:
    name: expense 
    external: true 
services:
    mysql:
      image: kedarnth9988/mysql:1.0 
      container_name: mysql 
    backend:
      image: kedarnath9988/backend:1.0 
      container_name: bakend 
      depends_on:
        - mysql 
    frontend:
      image: kedarnath9988/frontend:1.0 
      container_name: frontend 
      depends_on:
        - backend 
      expose:
        - 80:80
