name: expense 
networks:
  default:
    name: expense 
volumes:
  expense:
services:
    mysql:
      image: mysql:1.0 
      container_name: mysql 
      volumes:
        - source: expense
          target: /var/lib/mysql
          type:  volume
    backend:
      image: backend:1.1
      container_name: bakend 
      depends_on:
        - mysql 
    frontend:
      image: frontend:1.0 
      container_name: frontend 
      depends_on:
        - backend 
      expose:
        - 80:80
